### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by ensonic** [proteusvacuum/KlattSynth#1]
Thanks for sharing the project. Two requests:
Could you add to the README which version of puredata you have been using. I am trying to load it as:

```
puredata -pa formantSynth.pd
```

and I am missing some objects (output~, gate 2, spigot~, debounce 100, prepend set open). I am using 0.45.4 on Ubuntu 14.04 (Trusty).

Also it would be nice to briefly tell how to operate the patch. Thanks!

**Comment by proteusvacuum** [comment]
Hi @ensonic 
Thanks for your interest! This is something that I wrote in 2011, and is something that I put up on github more as a historical artefact of my school days, and isn't something that I expect will work any more. I'll add a note to the README.md to that effect. 

That being said, you might be able to get it running in puredata-exended, as I think most of those objects are present in that distribution. 

Good luck!
